#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("BusinessContactManager.Droid.Resource", IsApplication=true)]

namespace BusinessContactManager.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int CameraShy = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Dog1 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Dog2 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int green_button = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Icon = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int red_button = 2130837509;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060011
			public const int addContact = 2131099665;
			
			// aapt resource value: 0x7f060012
			public const int addEvent = 2131099666;
			
			// aapt resource value: 0x7f060006
			public const int companyEditText = 2131099654;
			
			// aapt resource value: 0x7f060005
			public const int companyLabel = 2131099653;
			
			// aapt resource value: 0x7f06001a
			public const int contactCompany = 2131099674;
			
			// aapt resource value: 0x7f060015
			public const int contactImage = 2131099669;
			
			// aapt resource value: 0x7f060018
			public const int contactName = 2131099672;
			
			// aapt resource value: 0x7f060014
			public const int contactsGrid = 2131099668;
			
			// aapt resource value: 0x7f060013
			public const int deleteContacts = 2131099667;
			
			// aapt resource value: 0x7f06000c
			public const int emailEditText = 2131099660;
			
			// aapt resource value: 0x7f06000b
			public const int emailLabel = 2131099659;
			
			// aapt resource value: 0x7f060002
			public const int firstNameEditText = 2131099650;
			
			// aapt resource value: 0x7f060001
			public const int firstNameLabel = 2131099649;
			
			// aapt resource value: 0x7f060003
			public const int lastNameLabel = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int lastNameLabelText = 2131099652;
			
			// aapt resource value: 0x7f060010
			public const int linearLayout1 = 2131099664;
			
			// aapt resource value: 0x7f06000e
			public const int notesEditText = 2131099662;
			
			// aapt resource value: 0x7f06000d
			public const int notesLabel = 2131099661;
			
			// aapt resource value: 0x7f06000a
			public const int phoneEditText = 2131099658;
			
			// aapt resource value: 0x7f060009
			public const int phoneLabel = 2131099657;
			
			// aapt resource value: 0x7f060000
			public const int relativeLayout1 = 2131099648;
			
			// aapt resource value: 0x7f06000f
			public const int save = 2131099663;
			
			// aapt resource value: 0x7f060016
			public const int tableLayout1 = 2131099670;
			
			// aapt resource value: 0x7f060017
			public const int tableRow1 = 2131099671;
			
			// aapt resource value: 0x7f060019
			public const int tableRow2 = 2131099673;
			
			// aapt resource value: 0x7f060008
			public const int titleEditText = 2131099656;
			
			// aapt resource value: 0x7f060007
			public const int titleLabel = 2131099655;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int ContactDetails = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ContactGrid = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int ContactGridCell = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int button_text = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
